language: php 
php:
  - 5.5
  - 5.6

env:
  - DB=MYSQL CORE_RELEASE=3.3
  - DB=PGSQL CORE_RELEASE=3.4

before_script:
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script: phpunit -c viewtemplate/ --coverage-clover=coverage.clover viewtemplate/tests

after_script:
  - mv coverage.clover viewtemplate/coverage.clover
  - cd viewtemplate
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
